// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATvRMcs4MY_temntRG3LwYWqd0ws_u_tA',
    appId: '1:992576190696:web:2bce3855a67bf302b8315d',
    messagingSenderId: '992576190696',
    projectId: 'todo-list-24e35',
    authDomain: 'todo-list-24e35.firebaseapp.com',
    storageBucket: 'todo-list-24e35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqI89np_e8etPJ8m750Ig8D458EIDy_e8',
    appId: '1:992576190696:android:6b7c73b870117691b8315d',
    messagingSenderId: '992576190696',
    projectId: 'todo-list-24e35',
    storageBucket: 'todo-list-24e35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPGf9qQ4TAU-IjGh5DA7jX0BNtCI4PpBo',
    appId: '1:992576190696:ios:cb111774ee4887acb8315d',
    messagingSenderId: '992576190696',
    projectId: 'todo-list-24e35',
    storageBucket: 'todo-list-24e35.appspot.com',
    iosClientId: '992576190696-naage70l05l83gqdnvgv1ancinalkqs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiA3Rohan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPGf9qQ4TAU-IjGh5DA7jX0BNtCI4PpBo',
    appId: '1:992576190696:ios:5f613d49b7c81cf9b8315d',
    messagingSenderId: '992576190696',
    projectId: 'todo-list-24e35',
    storageBucket: 'todo-list-24e35.appspot.com',
    iosClientId: '992576190696-7cc0l4pfhgp7kvh8kbin12fgno62thos.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiA3Rohan.RunnerTests',
  );
}
